import type { CaptureRecord } from '../types.ts';
import { captureQualityIssues } from './capture-quality.ts';
export interface PerformanceDiagnostic { id: string; title: string; evidence: string; nextStep: string }
export function performanceDiagnostics(record: CaptureRecord): PerformanceDiagnostic[] {
  const result: PerformanceDiagnostic[] = [];
  const add = (id: string, title: string, evidence: string, nextStep: string) => result.push({ id, title, evidence, nextStep });
  const s = record.summary, t = record.telemetrySummary;
  const issues = captureQualityIssues(record);
  if (issues.length) add('quality', 'Verify the measurement first', issues.join(' '), 'Recalculate older recordings, or repeat a short capture of the same gameplay scene. Do not choose tweaks from an unreliable FPS result.');
  if (!s || record.status !== 'completed') return result;
  if (!issues.length && s.onePercentLow != null && s.onePercentLow < s.averageFps * .65) add('pacing', 'Slow frames are pulling down the lows', `The 1% low is ${s.onePercentLow.toFixed(1)} FPS versus ${s.averageFps.toFixed(1)} average FPS.`, 'Inspect the timeline for scene transitions or hitches. Repeat a warmed-up route, then test one change at a time. This ratio alone cannot identify CPU, GPU, storage or shader-compilation stalls.');
  if (!issues.length && s.slowFrames50ms) add('hitches', 'Long frame intervals were measured', `${s.slowFrames50ms.toLocaleString()} intervals exceeded 50 ms; ${s.slowFrames100ms ?? 0} exceeded 100 ms. Loading screens and pauses are included.`, 'Compare the same scene after shader preparation. Check background work and game storage if hitches persist; do not clear shader caches between comparison runs.');
  if (s.displayed && Math.abs(s.displayed.averageFps / s.averageFps - 1) > .15) add('display', 'Application and display rates differ', `Application cadence: ${s.averageFps.toFixed(1)} FPS. Displayed cadence: ${s.displayed.averageFps.toFixed(1)} FPS.`, 'Compare counters over the same interval. Check V-Sync, FPS caps, presentation mode and frame generation. Display tracking is not a measurement of game simulation rate or input latency.');
  if (t?.gpu.samples && t.gpu.samples >= 3 && t.gpu.averagePercent != null && t.gpu.averagePercent >= 95) add('gpu', 'Sustained GPU load is worth testing', `Overall GPU load averaged ${t.gpu.averagePercent.toFixed(1)}% across ${t.gpu.samples} samples.`, 'Test a lower render scale or one lower shadow/effects setting in the same scene. If FPS improves consistently, GPU rendering is a candidate limit. Other apps and capture workloads also use the GPU.');
  if (t?.busiestCore && t.busiestCore.samples >= 3 && (t.busiestCore.averagePercent ?? 0) >= 85) add('cpu-core', 'A logical CPU stayed busy', `The busiest logical CPU per sample averaged ${t.busiestCore.averagePercent!.toFixed(1)}%; this can be hidden by low overall CPU usage.`, 'Inspect per-thread activity and background processes. Compare a lower crowd/view-distance setting if the game supports it. CPU scheduling and overall system samples cannot prove a game-thread bottleneck.');
  else if (t?.cpu.samples && t.cpu.samples >= 3 && (t.cpu.averagePercent ?? 0) >= 85) add('cpu', 'Overall CPU use was high', `CPU use averaged ${t.cpu.averagePercent!.toFixed(1)}%.`, 'Inspect competing processes. If streaming with CPU encoding, compare a supported hardware encoder while checking output quality. Overall load alone does not prove a CPU bottleneck.');
  if (t?.memory.samples && t.memory.samples >= 3 && (t.memory.peakPercent ?? 0) >= 90) add('ram', 'Review system memory headroom', `System RAM use peaked at ${t.memory.peakPercent!.toFixed(1)}%.`, 'Close unneeded apps and inspect paging during hitches. Keep the system-managed page file enabled. High RAM usage alone is not proof of paging stalls.');
  if (t?.gpuMemory && t.gpuMemory.samples >= 3 && (t.gpuMemory.peakPercent ?? 0) >= 90) add('vram', 'Review dedicated GPU memory use', `Device memory use peaked at ${t.gpuMemory.peakPercent!.toFixed(1)}% of reported capacity.`, 'Test one lower texture setting if hitches coincide with memory pressure. These are device-wide allocations, not proof of VRAM eviction or a game-only bottleneck.');
  if (t?.obs.renderingLagPercent != null && t.obs.renderingLagPercent > 1) add('obs-render', 'OBS rendering missed frames', `${t.obs.renderingLagPercent.toFixed(2)}% rendering lag was measured.`, 'Test a sustainable game FPS cap or a simpler OBS scene. Leave GPU headroom and compare both gameplay and output quality.');
  if (t?.obs.encodingLagPercent != null && t.obs.encodingLagPercent > 1) add('obs-encode', 'OBS encoding missed frames', `${t.obs.encodingLagPercent.toFixed(2)}% encoding lag was measured.`, 'Test a faster encoder preset or lower recording resolution/FPS. Review the quality tradeoff.');
  if (t?.obs.networkDropPercent != null && t.obs.networkDropPercent > 1) add('obs-network', 'OBS reported network drops', `${t.obs.networkDropPercent.toFixed(2)}% stream drops were measured.`, 'Check upload capacity and ingest routing. Lowering game graphics does not resolve network congestion.');
  add('limits', 'What this run cannot establish', 'Aggregate CPU/GPU load and peak temperatures do not identify the cause of each hitch. Clocks, throttle flags, disk activity and shader events were not captured.', 'Use repeated matched runs. Keep the same scene, frame-generation setting, FPS cap and workload. Review suggested changes and restore their backup if performance worsens.');
  return result;
}
