import type { SystemScan, TweakStatusReport, CaptureOptions, TelemetrySummary } from '../types.ts';
import { matchGame } from '../data/game-profiles.ts';

export interface Recommendation { id: string; title: string; reason: string; tradeoff: string; priority: 'Start here' | 'Worth testing' | 'Measured signal'; mode: 'automatic' | 'guided'; configured: boolean; stateKnown: boolean }
export function recommend({ processName, context, hardware, settings, telemetry, usesWindowsCapture = true }: { processName: string; context: CaptureOptions['context']; hardware: SystemScan | null; settings: TweakStatusReport | null; telemetry?: TelemetrySummary; usesWindowsCapture?: boolean }) {
  const game = matchGame(processName), items: Recommendation[] = [];
  const states = new Map(settings?.tweaks.map(t => [t.id, t]) ?? []);
  const gpu = hardware?.gpu.name ?? '', nvidia = /NVIDIA|GeForce/i.test(gpu), rtx = /RTX\s*\d/i.test(gpu);
  const desktopRtx = /RTX\s*(?:20|30|40|50)\d\d/i.test(gpu);
  function add(id: string, title: string, reason: string, tradeoff: string, priority: Recommendation['priority'] = 'Worth testing', mode: Recommendation['mode'] = 'guided') {
    if (items.some(item => item.id === id)) return;
    const state = states.get(id);
    items.push({ id, title, reason, tradeoff, priority, mode, configured: state?.status === 'enabled', stateKnown: !!state && state.status !== 'unknown' });
  }
  if (processName.trim()) {
    add('game-mode', 'Windows Game Mode', `Test scheduling behavior while ${game.id === 'generic' ? 'your game or program' : game.name} competes with background work.`, 'A starting point, not a promised FPS increase. Some workloads may behave differently.', 'Start here', 'automatic');
    add('fps-cap', 'Find a sustainable frame-rate cap', context === 'Gaming' ? 'A sustainable cap can improve frame pacing and leave room for demanding scenes.' : 'Leave GPU headroom for both the game and OBS composition.', 'A lower cap reduces peak FPS. Prefer stable lows and check your monitor/VRR setup.', 'Start here');
    add('overlay-audit', 'Review overlapping overlays', 'Multiple overlays and recording hooks can add work to the selected game.', 'Keep the overlays, accessibility tools, and capture functions you actually need. Change one at a time.');
  }
  if (!usesWindowsCapture && context !== 'Gaming') add('game-dvr', 'Disable unused Windows game capture', 'You indicated that you do not use Game Bar recording or background replays.', 'This disables Windows recording features. OBS/NVIDIA capture must be configured separately.', 'Worth testing', 'automatic');
  if (nvidia && game.reflex) add('nvidia-reflex', 'Check in-game NVIDIA Reflex', `${game.name} has an in-game Reflex setting to check on your ${gpu}. Start with On.`, 'This targets render-queue latency, which FPS alone cannot measure. On + Boost can increase power use.', 'Start here');
  if (game.competitive) add('raw-input', 'Use the game’s raw mouse input path', `${game.name} is a competitive game; consistent input is a separate goal from maximum FPS.`, 'Some games always use raw input and have no switch. Windows pointer acceleration does not affect those paths.');
  if (rtx && game.dlss) add('dlss-quality', 'Test DLSS Quality if GPU limited', `Your ${gpu} supports DLSS Super Resolution; check availability in ${game.name} and the selected rendering mode.`, 'It can soften the image, especially at 1080p. Lower render resolution helps less when CPU limited.');
  if (hardware?.gpu.vramGB != null && hardware.gpu.vramGB <= 8) add('vram-budget', 'Review the texture memory budget', `Windows reports ${hardware.gpu.vramGB} GB of dedicated VRAM on ${gpu}. Demanding textures can exceed available memory.`, 'Lower textures only if hitching and memory pressure coincide. VRAM capacity or allocation alone does not prove a bottleneck.');
  if (game.rayTracing && hardware) add('ray-tracing', 'Measure the cost of ray tracing', `${game.name} offers expensive lighting settings in supported rendering modes. Compare one level at a time.`, 'Reducing these effects changes image quality. First check that they are actually enabled.');
  if (hardware?.memory.totalGB != null && hardware.memory.totalGB <= 16) add('browser-tabs', 'Reduce competing memory use', `Your scan reports ${hardware.memory.totalGB} GB RAM. Browser tabs and capture apps can compete with demanding games.`, 'Close only applications you do not need. Keep the system-managed page file enabled.');
  if (hardware?.storage.totalGB && hardware.storage.freeGB != null && hardware.storage.freeGB / hardware.storage.totalGB < .1) add('storage-cleanup', 'Review low storage headroom', `Your scan reports ${hardware.storage.freeGB} GB free across local drives. Inspect the game and recording drives individually.`, 'The scan total does not identify which drive is constrained. Review files before deleting anything.');
  if (hardware && /Ryzen.*5[0-9]{3}/i.test(hardware.cpu.name)) add('ryzen-balanced', 'Keep Balanced as your power-plan baseline', `Your ${hardware.cpu.name} does not automatically need High performance. Compare sustained clocks and frame times first.`, 'High performance may increase heat and idle power without improving gameplay. Restore center can restore a saved plan.');
  if (hardware?.cpu.cores != null && hardware.cpu.cores <= 6 && context !== 'Gaming') add('encoder-choice', 'Review CPU encoder contention', `Your scan reports ${hardware.cpu.cores} CPU cores. A heavy CPU encoder may compete with the game.`, 'Check OBS Stats and compare a supported GPU encoder. Core count alone does not predict performance.');
  if (context !== 'Gaming') {
    add('obs-headroom', 'Check OBS rendering and encoding lag', 'During the same scene, open OBS → View → Stats and distinguish rendering lag from encoding lag and network drops.', 'This app does not read OBS statistics. Reset OBS Stats before each test and compare the same workload.', 'Start here');
    add('obs-game-capture', 'Try a direct OBS Game Capture source', 'A direct game source can avoid capturing the entire desktop when the game supports it.', 'Protected games may require a different supported capture method. Keep capture method unchanged within an experiment.');
    if (desktopRtx) add('obs-nvenc-h264', 'Test the dedicated NVIDIA encoder', `Your ${gpu} has NVENC. Test it if CPU encoding competes with gameplay. H.264 is widely supported.`, 'Choose a compatible output format and bitrate; hardware encoding still uses GPU resources.');
    if (/RTX\s*(?:40|50)\d\d/i.test(gpu) && context === 'Recording') add('obs-nvenc-av1', 'Consider NVENC AV1 recording', `Your ${gpu} supports AV1 encoding for workflows that accept it.`, 'Check editor/player compatibility. Better compression is not a guaranteed FPS improvement.');
    if (context === 'Streaming') add('upload-budget', 'Keep stream upload headroom', 'Network congestion can drop stream frames even when the game runs well.', 'OBS network drops are not game FPS or encoding lag. Confirm the actual upload rate first.');
  }
  if (telemetry?.enabled && telemetry.cpu.samples >= 3 && telemetry.cpu.averagePercent != null && telemetry.cpu.averagePercent >= 85) add('startup-apps', 'Inspect high overall CPU use', `The selected run averaged ${telemetry.cpu.averagePercent.toFixed(0)}% overall CPU use. Identify competing processes before testing a change.`, 'Overall CPU use does not prove a game is CPU limited and can hide a single saturated core.', 'Measured signal');
  if (telemetry?.enabled && telemetry.gpu.samples >= 3 && telemetry.gpu.averagePercent != null && telemetry.gpu.averagePercent >= 95) add('gpu-load-review', 'Investigate sustained GPU load', `The selected run averaged ${telemetry.gpu.averagePercent.toFixed(0)}% GPU utilization on ${telemetry.gpu.name}.`, 'This is whole-GPU load, including OBS and other apps. Test a lower render resolution or a sustainable cap; it is not definitive bottleneck detection.', 'Measured signal');
  if (telemetry?.enabled && telemetry.memory.samples >= 3 && telemetry.memory.peakPercent != null && telemetry.memory.peakPercent >= 90) add('memory-load-review', 'Investigate memory pressure', `System RAM use peaked at ${telemetry.memory.peakPercent.toFixed(0)}% in this run. Inspect competing apps and paging.`, 'Do not disable the page file or use a RAM cleaner. Memory use alone does not show paging stalls.', 'Measured signal');
  if (telemetry?.obs.renderingLagPercent != null && telemetry.obs.renderingLagPercent > 1) add('obs-render-lag', 'Reduce observed OBS rendering lag', `OBS missed ${telemetry.obs.renderingLagPercent.toFixed(2)}% of rendered frames during the selected run.`, 'Test a sustainable game FPS cap, simpler OBS scenes, or lower output resolution. Rendering lag differs from encoder overload.', 'Measured signal');
  if (telemetry?.obs.encodingLagPercent != null && telemetry.obs.encodingLagPercent > 1) add('obs-encode-lag', 'Reduce observed OBS encoding lag', `OBS skipped ${telemetry.obs.encodingLagPercent.toFixed(2)}% of output frames during the selected run.`, 'Test a faster encoder preset or lower output resolution/FPS. This may reduce recording quality.', 'Measured signal');
  if (telemetry?.obs.networkDropPercent != null && telemetry.obs.networkDropPercent > 1) add('obs-network-lag', 'Review observed stream drops', `OBS reported ${telemetry.obs.networkDropPercent.toFixed(2)}% dropped stream frames during the selected run.`, 'Check upload capacity and server routing; lowering game graphics does not fix network congestion.', 'Measured signal');
  return { game, items, hardwareKnown: !!hardware, gpuKnown: !!hardware && !/not reported|unknown/i.test(gpu) };
}
