"""Recommendations UI integration. Windows/hardware/OBS responses are fixtures."""
import json
from pathlib import Path
from datetime import datetime,timedelta,timezone
import os
from playwright.sync_api import sync_playwright,expect
root=Path(__file__).resolve().parents[1]
ids=[r['id'] for r in json.loads((root/'scripts/windows/tweaks.json').read_text())]
hardware={'cpu':{'name':'AMD Ryzen 9 5900X','cores':12,'threads':24},'gpu':{'name':'NVIDIA GeForce RTX 4060','vramGB':8,'driverVersion':'32.0.15.1234'},'memory':{'totalGB':32,'speedMHz':3200},'os':{'name':'Windows 11','build':'26200'},'storage':{'totalGB':2000,'freeGB':1200},'scannedAt':'2026-10-08T00:00:00Z','peripherals':[]}
def states(after=False):return {'checkedAt':'2026-10-08T00:00:00Z','tweaks':[{'id':id,'status':'enabled' if after and id=='game-mode' else 'not-enabled','message':'Test fixture','fingerprint':('b' if after and id=='game-mode' else 'a')*64} for id in ids]}
records=[]
for phase in ['before','after']:
 for i in range(3):
  start=datetime(2026,10,8,1 if phase=='before' else 3,i*3,tzinfo=timezone.utc)
  records.append({'id':phase+str(i),'processName':'FortniteClient-Win64-Shipping.exe','context':'Gaming','phase':phase,'seconds':120,'scenario':'Same replay','telemetry':True,'benchmark':{'experiment':'Game Mode experiment','resolution':'1080p','graphics':'Low native','gameBuild':'123','fpsCap':0,'verified':True},'version':1,'status':'completed','startedAt':start.isoformat(),'endedAt':(start+timedelta(seconds=120)).isoformat(),'collector':'PresentMon 2.3.0','settings':states(phase=='after'),'settingsEnd':states(phase=='after'),'hardware':hardware,'hardwareKey':'same','summary':{'metricsVersion':2,'measurementBasis':'cpu-start-interval','qualityIssues':[],'frames':12000,'sampledSeconds':120,'averageFps':110 if phase=='after' else 100,'onePercentLow':66 if phase=='after' else 60,'p95FrameMs':18 if phase=='after' else 20,'otherStreamFrames':0,'invalidFrames':0,'processId':12},'error':'','telemetrySummary':{'enabled':True,'intervalSeconds':5,'cpu':{'samples':20,'averagePercent':45,'peakPercent':60},'memory':{'samples':20,'averagePercent':60,'peakPercent':70},'gpu':{'name':hardware['gpu']['name'],'samples':20,'averagePercent':97,'peakPercent':99,'peakTemperatureC':70},'cpuTemperatureC':65,'cpuTemperatureSensor':'CPU (Tctl/Tdie)','obs':{'samples':0,'renderingLagPercent':None,'encodingLagPercent':None,'networkDropPercent':None,'streaming':False,'recording':False},'warnings':[]}})
fixture='''(() => { const hardware=HARDWARE,states=STATES,records=RECORDS;let obs=false;window.tweaker={scan:async()=>hardware,getTweakStatus:async()=>states,listBackups:async()=>[],getDisplayModes:async()=>[],captureStatus:async()=>({active:false}),listCaptures:async()=>records,obsStatus:async()=>({connected:obs}),connectObs:async()=>{obs=true;return {connected:true}},disconnectObs:async()=>{obs=false},listPrograms:async()=>['FortniteClient-Win64-Shipping.exe']}; })();'''.replace('HARDWARE',json.dumps(hardware)).replace('STATES',json.dumps(states(True))).replace('RECORDS',json.dumps(records))
artifacts=Path('/tmp/tweakerzzz-validation');artifacts.mkdir(exist_ok=True)
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox']);page=b.new_page(viewport={'width':1440,'height':1000});errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.add_init_script(fixture);page.goto(os.environ.get('TWEAKER_URL','http://127.0.0.1:5173'),wait_until='networkidle');page.screenshot(path=str(artifacts/'bubblegum-overview.png'),full_page=True)
 assert page.evaluate('getComputedStyle(document.documentElement).getPropertyValue("--pink").trim()')=='#ff4fa3'
 page.get_by_role('button',name='FPS recorder',exact=True).click();page.get_by_label('Game profile',exact=True).select_option('fortnite');page.get_by_role('button',name='Scan for recommendations').click();expect(page.locator('.game-advisor')).to_contain_text('AMD Ryzen 9 5900X');expect(page.locator('.game-advisor')).to_contain_text('NVIDIA Reflex');expect(page.get_by_role('button',name='Already configured — skipped')).to_be_disabled();expect(page.locator('.evidence-card')).to_contain_text('Repeated improvement');expect(page.locator('.evidence-card')).to_contain_text('3 independent pairs')
 page.locator('.advisor-select select').select_option('after2');expect(page.locator('.advisor-cards')).to_contain_text('Investigate sustained GPU load');page.locator('.game-advisor').screenshot(path=str(artifacts/'bubblegum-recommendations.png'))
 page.get_by_role('combobox',name='WORKLOAD',exact=True).select_option('Streaming');expect(page.locator('.advisor-cards')).to_contain_text('Test NVIDIA NVENC H.264');page.get_by_label('I use Windows Game Bar recording or background replays').uncheck();page.locator('.advisor-card').filter(has_text='Disable unused Windows game capture').get_by_role('button',name='Review this tweak').click();expect(page.get_by_role('dialog')).to_contain_text('Disable Windows game capture');page.get_by_role('button',name='Keep editing').click();page.get_by_role('button',name='Clear',exact=True).click()
 page.locator('.obs-connection summary').click();page.get_by_label('OBS PASSWORD').fill('test-secret');page.get_by_role('button',name='Connect to OBS',exact=True).click();expect(page.locator('.obs-connection summary')).to_contain_text('Connected locally');expect(page.get_by_label('OBS PASSWORD')).to_have_value('')
 page.get_by_label('Use controlled benchmark conditions',exact=False).check();page.get_by_label('EXPERIMENT NAME',exact=True).fill('One tweak');page.get_by_label('GAME RESOLUTION',exact=True).fill('1080p');page.get_by_label('GRAPHICS, UPSCALING & FRAME GENERATION').fill('Low native FG off');page.get_by_label('GAME BUILD / PATCH').fill('123');page.get_by_label('I warmed up this scene',exact=False).check()
 for width in [390,900,1366]:
  page.set_viewport_size({'width':width,'height':1000})
  assert page.evaluate('document.documentElement.scrollWidth <= innerWidth'),width
 assert not errors,errors
 print('PASS: game/hardware rules, configured-tweak skipping, repeated evidence, measured signals, review flow, OBS setup, controlled benchmark form and responsive bubblegum UI (mocked native responses).')
 b.close()
