import { useState } from 'react';
import { ComponentVersions } from './ComponentVersions';
import { visibleParts } from '../lib/driver-visibility';
import { ArrowUpRight, History, LoaderCircle, RefreshCw } from 'lucide-react';
import type { ComponentUpdateReport, DriverHistory, DriverInstallLog, DriverReport, DriverUpdateOffers } from '../types';
const show = (value: string | number | boolean | null | undefined) => value === null || value === undefined || value === '' ? 'Not reported' : typeof value === 'boolean' ? value ? 'Yes' : 'No' : String(value);
const when = (value: string | null) => value ? new Date(value).toLocaleString() : 'Not yet';
const changeLabels = { 'first-seen': 'First observed', 'not-reported': 'No longer reported', 'driver-changed': 'Driver details changed', 'device-changed': 'Device state changed', 'firmware-changed': 'Firmware version changed', 'component-changed': 'Hardware details changed' };
const fieldLabels: Record<string, string> = { version: 'Driver version', provider: 'Driver provider', driverDate: 'Driver release date', infName: 'INF package', signed: 'Reported signed', signer: 'Reported signer', driverReported: 'Driver record reported', name: 'Device name', category: 'Device class', manufacturer: 'Manufacturer', service: 'Driver service', status: 'Windows status', present: 'Present', problemCode: 'Windows problem code' };

export function HardwareParts({ report, openSource, versions, checking, openRelease }: { report: DriverReport; openSource: (id: string) => void; versions: ComponentUpdateReport | null; checking: boolean; openRelease: (id: string) => void }) {
  const [query, setQuery] = useState(''), [category, setCategory] = useState('All components');
  const parts = visibleParts(report);
  const filtered = parts.filter(c => (category === 'All components' || category === c.category) && `${c.name} ${Object.values(c.values).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  return <section aria-label="Detected hardware components">
    <div className="driver-toolbar"><label className="field-label">COMPONENT<select aria-label="Hardware component category" value={category} onChange={e => setCategory(e.target.value)}><option>All components</option>{[...new Set(parts.map(c => c.category))].map(c => <option key={c}>{c}</option>)}</select></label><label className="field-label">FIND A PART<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Graphics card, processor, BIOS, keyboard…"/></label></div>
    <div className="component-cards">{filtered.map(c => <article className="panel component-card" key={c.id}><span className="pill">{c.category}</span><h3>{c.name}</h3><ComponentVersions component={c} devices={report.devices.filter(d => c.deviceIds.includes(d.id))} update={versions?.items.find(v => v.componentId === c.id)} busy={checking} openRelease={openRelease}/><details className="component-details"><summary>Hardware & installed driver details</summary><dl>{Object.entries(c.values).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{show(value)}</dd></div>)}</dl><p className="body-copy">{c.note}</p></details>{c.source ? <button className="button secondary" onClick={() => openSource(c.source!)}>Official updates & release notes<ArrowUpRight size={15}/></button> : <p className="fine-print">Manufacturer lookup needed. Use the exact part or system model; no update match is assumed.</p>}<small>{c.sourceName ? `${c.sourceName} · select the exact model to read available versions and release notes.` : 'An unknown vendor stays unidentified.'}</small></article>)}</div>
    {!filtered.length && <p className="body-copy">No component details match. Scan again if this report predates component detection.</p>}
  </section>;
}

export function DriverOffers({ offers, busy, check, cancel, openLink, report }: { offers: DriverUpdateOffers | null; busy: boolean; check: () => void; cancel: () => void; openLink: (id: string, index: number) => void; report: DriverReport | null }) {
  return <section className="panel driver-offers"><h2>Available driver & firmware offers</h2><p className="body-copy">Check the PC’s configured Windows Update source for applicable driver packages, including firmware where offered. No packages are downloaded or installed. This is not a universal latest-version check: manufacturer releases may be newer or absent from Windows Update.</p>
    <button className="button primary" disabled={busy || !window.tweaker?.checkDriverUpdates} onClick={check}>{busy ? <LoaderCircle className="spin" size={17}/> : <RefreshCw size={17}/>}Check driver update offers</button>
    {busy && <p className="fine-print" role="status">Windows is checking its configured update source. This can take up to two minutes. Finish this check before recording FPS.</p>}
    {busy && <button className="button secondary" onClick={cancel}>Cancel driver update check</button>}
    {offers && <><div className="notice-panel"><strong>{offers.complete ? 'Update source checked' : 'Partial update search'}</strong><p>{offers.message}</p><small>{offers.source} · {when(offers.checkedAt)}</small></div>{offers.packages.map(p => {
      const matched = (report?.devices || []).filter(d => [d.instanceId, ...(d.hardwareIds || []), ...(d.compatibleIds || [])].some(id => id && id.toUpperCase() === p.hardwareId.toUpperCase()));
      return <article className="driver-offer-card" key={p.id}><span className="pill">Offered for this PC</span><h3>{p.title}</h3><p>{[p.manufacturer, p.model, p.driverClass].filter(Boolean).join(' · ')}</p><p className="fine-print">{matched.length ? `Hardware ID matches: ${matched.map(d => d.name).join(' · ')}` : 'Component association unavailable; Windows Update determined applicability to this PC.'}</p><p className="fine-print">Driver release date: {show(p.driverDate)} · Catalog revised: {show(p.catalogDate)}</p><details><summary>Published package information & release links</summary><p className="driver-release-text">{p.description || 'No package description was supplied.'}</p><p className="fine-print">This is the publisher’s Windows Update package description. Full changes, known issues and prerequisites may only appear on the manufacturer’s model-specific release page.</p><div className="button-row">{p.links.map((link, i) => <button key={i} className="button secondary" onClick={() => openLink(p.id, i)}>Release information · {link.label}<ArrowUpRight size={15}/></button>)}</div>{!p.links.length && <p className="fine-print">No recognized official release link was supplied. Use the component’s manufacturer support page.</p>}</details></article>;
    })}</>}
    <p className="fine-print">The package title is shown as published; a separate version is not invented when the source omits one. For BIOS/UEFI, verify the exact motherboard or OEM system and revision on its official page. “No offers” does not mean “latest BIOS verified.”</p>
  </section>;
}

export function DriverChangeHistory({ history, log, busy, setMonitoring, clear, loadLog, refresh }: { history: DriverHistory | null; log: DriverInstallLog | null; busy: boolean; setMonitoring: (v: boolean) => void; clear: () => void; loadLog: () => void; refresh: () => void }) {
  const [query, setQuery] = useState(''), [type, setType] = useState('All changes'), [page, setPage] = useState(0), [confirm, setConfirm] = useState(false);
  const changes = (history?.changes || []).filter(c => (type === 'All changes' || type === c.kind) && `${c.name} ${c.category} ${c.fields.map(f => `${f.before} ${f.after}`).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const index = Math.min(page, Math.max(0, Math.ceil(changes.length / 25) - 1));
  return <section className="panel driver-history"><h2><History size={21}/> Local hardware & driver history</h2><p className="body-copy">The first complete scan establishes a baseline. Later scans record changed driver versions, BIOS/storage firmware, component details and device states. “Observed” is when Tweakerzzz noticed a difference, not the exact installation time. Intermediate changes between scans can be missed.</p>
    <label className="check-label"><input type="checkbox" disabled={busy || !history || !window.tweaker?.setDriverMonitoring} checked={!!history?.monitorEnabled} onChange={e => setMonitoring(e.target.checked)}/>Check for changes every 15 minutes while Tweakerzzz is open</label><p className="fine-print">Off by default. These local scans add brief CPU work and pause during FPS recording and app-managed Windows changes. No startup service is installed. They do not check online update availability. Closing the app stops checks.</p>
    {history && <><p className="fine-print">Baseline: {when(history.baselineAt)} · Last complete scan: {when(history.lastScanAt)} · {history.scans} scans · Up to {history.limit} changes retained.</p><p className="body-copy" role="status">{history.message}</p></>}
    <div className="driver-toolbar"><label className="field-label">CHANGE TYPE<select value={type} onChange={e => { setType(e.target.value); setPage(0); }}><option>All changes</option>{Object.entries(changeLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="field-label">FIND A CHANGE<input value={query} onChange={e => { setQuery(e.target.value); setPage(0); }} placeholder="BIOS, graphics card, version…"/></label></div>
    {!changes.length && <p className="body-copy">{history?.baselineAt ? 'No matching changes have been recorded.' : 'Scan your hardware to start local change history.'}</p>}
    <div className="driver-change-list">{changes.slice(index * 25, index * 25 + 25).map(c => <article key={c.id}><div className="section-heading"><h3>{c.name}</h3><span className="pill">{changeLabels[c.kind]}</span></div><p className="fine-print">{c.category} · Observed {when(c.observedAt)} · Previous observation {when(c.previousScanAt)}</p>{c.kind === 'first-seen' || c.kind === 'not-reported' ? <p className="body-copy">A scan difference does not prove installation or removal; connection, enumeration and hardware changes can also affect reporting.</p> : <dl>{c.fields.map(f => <div key={f.field}><dt>{fieldLabels[f.field] || f.field}</dt><dd>{show(f.before)} → {show(f.after)}</dd></div>)}</dl>}</article>)}</div>
    <div className="button-row driver-pagination"><button className="button secondary" disabled={!index} onClick={() => setPage(index - 1)}>Previous changes</button><span>Page {index + 1} of {Math.max(1, Math.ceil(changes.length / 25))}</span><button className="button secondary" disabled={(index + 1) * 25 >= changes.length} onClick={() => setPage(index + 1)}>Next changes</button><button className="button secondary" disabled={busy || !window.tweaker?.getDriverHistory} onClick={refresh}>Refresh saved history</button><button className="button secondary" disabled={busy || !window.tweaker?.clearDriverHistory} onClick={() => setConfirm(true)}>Clear local history</button></div>
    {confirm && <div className="callout"><p>Delete this app’s hardware/driver history and baseline? This also turns background checks off. Installed drivers and Windows logs stay unchanged.</p><div className="button-row"><button className="button secondary" onClick={() => setConfirm(false)}>Keep history</button><button className="button secondary" disabled={busy} onClick={() => { setConfirm(false); clear(); }}>Delete local history</button></div></div>}
    <details className="windows-install-log"><summary>Windows installation log · additional evidence</summary><p className="body-copy">Windows may retain installation operations from before Tweakerzzz was installed. These are separate from manufacturer release notes and our scan comparisons.</p><button className="button secondary" disabled={busy || !window.tweaker?.getDriverInstallLog} onClick={loadLog}>Read Windows installation log</button>{log && <><p className="fine-print">{log.message}</p>{log.entries.map((entry, i) => <article key={entry.id + i}><strong>{entry.operation}</strong><p>{entry.localTime || 'Time not reported'} · Windows local log time · {entry.result}</p><p className="fine-print">{entry.detail}</p>{entry.instanceId && <details><summary>Associated instance ID</summary><code>{entry.instanceId}</code></details>}</article>)}</>}</details>
  </section>;
}
